### ISSUE TITLE
[Bug] net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:#if

### ISSUE THREAD

**Issue by Inrixia** [GeForceLegend/SEUS_PTGI_GFME#5]
I am running into the following crash when attempting to run this shader... Any ideas?
```
[28Nov2022 18:16:29.662] [Render thread/ERROR] [Oculus/]: Failed to create shader rendering pipeline, disabling shaders!
net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:#if
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:37) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.resources.ResourceLocation.<init>(ResourceLocation.java:46) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.coderbot.iris.block_rendering.BlockMaterialMapping.addBlockStates(BlockMaterialMapping.java:67) ~[oculus-1.4.3.jar%23203!/:?]
	at net.coderbot.iris.block_rendering.BlockMaterialMapping.lambda$createBlockStateIdMap$0(BlockMaterialMapping.java:30) ~[oculus-1.4.3.jar%23203!/:?]
	at it.unimi.dsi.fastutil.ints.Int2ObjectMap.lambda$forEach$0(Int2ObjectMap.java:253) ~[fastutil-8.5.6.jar%2341!/:?]
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$MapEntrySet.fastForEach(Int2ObjectOpenHashMap.java:1077) ~[fastutil-8.5.6.jar%2341!/:?]
	at it.unimi.dsi.fastutil.ints.Int2ObjectMap.forEach(Int2ObjectMap.java:255) ~[fastutil-8.5.6.jar%2341!/:?]
	at it.unimi.dsi.fastutil.ints.Int2ObjectMaps$UnmodifiableMap.forEach(Int2ObjectMaps.java:691) ~[fastutil-8.5.6.jar%2341!/:?]
	at net.coderbot.iris.block_rendering.BlockMaterialMapping.createBlockStateIdMap(BlockMaterialMapping.java:28) ~[oculus-1.4.3.jar%23203!/:?]
	at net.coderbot.iris.pipeline.newshader.NewWorldRenderingPipeline.<init>(NewWorldRenderingPipeline.java:355) ~[oculus-1.4.3.jar%23203!/:?]
	at net.coderbot.iris.Iris.createPipeline(Iris.java:647) ~[oculus-1.4.3.jar%23203!/:?]
	at net.coderbot.iris.pipeline.PipelineManager.preparePipeline(PipelineManager.java:34) ~[oculus-1.4.3.jar%23203!/:?]
	at net.coderbot.iris.Iris.reload(Iris.java:589) ~[oculus-1.4.3.jar%23203!/:?]
	at net.coderbot.iris.apiimpl.IrisApiV0ConfigImpl.setShadersEnabledAndApply(IrisApiV0ConfigImpl.java:28) ~[oculus-1.4.3.jar%23203!/:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.applyChanges(ShaderPackScreen.java:524) ~[oculus-1.4.3.jar%23203!/:?]
	at net.coderbot.iris.gui.screen.ShaderPackScreen.lambda$init$1(ShaderPackScreen.java:209) ~[oculus-1.4.3.jar%23203!/:?]
	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:40) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:111) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:528) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar%2348!/:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%2344!/:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar%2348!/:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:197) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:333) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1068) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23277!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
```

**Comment by GeForceLegend** [comment]
https://github.com/IrisShaders/Iris/issues/1712
